name: GitHub Classroom Workflow

on: 
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/*'

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  Checking-Solution:
    runs-on: gtest
    timeout-minutes: 5
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Build
        run: |
             cmake .
             cmake --build .
      - name: Autograding
        uses: amcp-pit/autograding@v1
      - name: Memory leaks
        run: |
             valgrind --tool=memcheck --leak-check=full --undef-value-errors=no --error-exitcode=111 ./b tests/8-progr.txt tests/8-input.txt output.txt
      - name: Code linting
        uses: amcp-pit/cpp-linter@v1
        with:
          extra-args-before: '-xc++'
          extra-args: '-std=c++20'
          after-args: '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON'
      - name: Checkout
        uses: actions/checkout@v4
      - name: CPD
        uses: amcp-pit/cpd-action@v1
        id: cpd
        with:
          repository: ${{ github.repository }}
          collection: ${{ github.repository_owner  }}
      - name: Clean
        run: |
             rm -rf ./* || true
             rm -rf ./.??* || true
